-- ==============================================================================
-- FEITO DE NÓS — RATE LIMIT PERSISTENTE PARA PEDIDOS PÚBLICOS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.order_request_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_request_limits_ip_created_at
  ON public.order_request_limits (ip_hash, created_at DESC);

ALTER TABLE public.order_request_limits ENABLE ROW LEVEL SECURITY;

-- Sem policies públicas: apenas service_role acessa esta tabela pelo backend.

COMMENT ON TABLE public.order_request_limits IS
  'Registros efêmeros de tentativas de criação de pedido, usando hash salgado do IP.';
